### ISSUE TITLE
case-statements C tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMeCLikeIm5#14]
Populate C file with a tutorial and challenge.

**Comment by naz2001** [comment]
Can I be assigned this issue?

**Comment by funbeedev** [comment]
@naz2001 A small change is needed in your existing PR but sure after that you can submit a PR for this. You're assigned now!

**Comment by naz2001** [comment]
May I know what is the small change required?

**Comment by sabderemane** [comment]
@naz2001 It's linked to [my comment](https://github.com/inspirezonetech/TeachMeCLikeIm5/pull/40#pullrequestreview-777877229) and when someone will do the review of the both PR
