### ISSUE TITLE
[tutorial] Commenting C tutorial

### ISSUE THREAD

**Issue by balayokesh** [inspirezonetech/TeachMeCLikeIm5#39]
**Description of the tutorial**
Hi, I would like to add content to `1-getting-started/commenting.c`

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
...

**Comment by funbeedev** [comment]
@balayokesh sure, you're assigned now!
