### ISSUE TITLE
Update GitHub action to treat warnings as errors in compilation

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMeCLikeIm5#48]
**This issue is only for beginners to open source contributing!**

To solve this issue edit `.github/workflows/run-modified-c.sh`
Change this line:
```bash
    gcc $b && ./a.out
```
To this:
```bash
 gcc -Werror $b && ./a.out
```

**Comment by datsukai** [comment]
Can I be assigned this issue?

**Comment by funbeedev** [comment]
@datsukai Sure, you're assigned now!
