### ISSUE TITLE
relational-operators C tutorial 

### ISSUE THREAD

**Issue by mananuppadhyay** [inspirezonetech/TeachMeCLikeIm5#70]
**Description of the tutorial**
i'd like to create a tutorial on the use of relational operators in C

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
...

**Comment by hamzabohra** [comment]
Hi can i solve this one also?

**Comment by funbeedev** [comment]
@hamzabohra  Of course.
