### ISSUE TITLE
[tutorial] Ternary operator in C

### ISSUE THREAD

**Issue by pushpit-J19** [inspirezonetech/TeachMeCLikeIm5#76]
**Description of the tutorial**
A tutorial on using Ternary operators in C.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
Please assign me this issue under Hacktoberfest

**Comment by funbeedev** [comment]
@pushpit-J19 assigned,
