### ISSUE TITLE
Update repo - sort folders correctly

### ISSUE THREAD

**Issue by ropoko** [inspirezonetech/TeachMeCLikeIm5#81]
Just a visual correction in the repo, sorting the folders correctly, so it will follow an order:

"01-getting-started"
"02-variables"
...
"10-preprocessors"
...

I'm think that would be great as the project grows to find faster the subject you want.

**Comment by ropoko** [comment]
Also, if you want to assign me to this correction, I'll be glad to help

**Comment by funbeedev** [comment]
@ropoko Thanks for the suggestion! I've assigned this to you :)
