### ISSUE TITLE
[tutorial] Add printf function in common built-in functions

### ISSUE THREAD

**Issue by hamzabohra** [inspirezonetech/TeachMeCLikeIm5#91]
**Description of the tutorial**
I want add printf function as well is common built-in functions folder.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
 add this under hacktoberfest

**Comment by hamzabohra** [comment]
Please let me add this.

**Comment by funbeedev** [comment]
@hamzabohra  of course go ahead!
