### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by RR-08** [inspirezonetech/TeachMeCLikeIm5#95]
**Description of the tutorial**
A tutorial folder on creating, accessing, and modifying strings in the c program.

**Do you want to be assigned to work on this?**
(mark [x])
- [X] YES
- [ ] NO

**Optional: Any additional info you want to add**
It could be divided into three files including one for creating, accessing and modifying strings in c program.

**Comment by RR-08** [comment]
@sabderemane here is a new tutorial idea.  Would like to work on adding tutorials on strings. Your feedback and views on it.

**Comment by sabderemane** [comment]
You're assigned now @RR-08
